apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: khanhash1992/e-commerce-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083