apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-service
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
        tier: database
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-service-db-password
        - name: MYSQL_PRODUCT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: product-service-db-password
        - name: MYSQL_ORDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: order-service-db-password
        ports:
        - containerPort: 3306
          name: mysql-container
        volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
      - name: mysql-persistent-storage # Obtaining 'vloume' from PVC
        persistentVolumeClaim:
          claimName: mysql-pv-claim

        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
    tier: database
spec:
  selector:       # mysql Pod Should contain same labels
    app: mysql-service
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306