apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init-user-db.sql: |
    CREATE DATABASE IF NOT EXISTS user_service_db;
    CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON user_service_db.* TO 'username'@'%';
    FLUSH PRIVILEGES;
  init-product-db.sql: |
    CREATE DATABASE IF NOT EXISTS product_service_db;
    CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON product_service_db.* TO 'username'@'%';
    FLUSH PRIVILEGES;
  init-order-db.sql: |
    CREATE DATABASE IF NOT EXISTS order_service_db;
    CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON order_service_db.* TO 'username'@'%';
    FLUSH PRIVILEGES;
  # user-service-db-url: jdbc:mysql://user-service-mysql/user_service_db
  # product-service-db-url: jdbc:mysql://product-service-mysql/product_service_db
  # order-service-db-url: jdbc:mysql://order-service-mysql/order_service_db