apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-service-db-username: c3ByaW5nc3R1ZGVudA==
  mysql-service-db-password: c3ByaW5nc3R1ZGVudA==
  user-service-db-username: c3ByaW5nc3R1ZGVudA==
  user-service-db-password: c3ByaW5nc3R1ZGVudA==
  product-service-db-username: c3ByaW5nc3R1ZGVudA==
  product-service-db-password: c3ByaW5nc3R1ZGVudA==
  order-service-db-username: c3ByaW5nc3R1ZGVudA==
  order-service-db-password: c3ByaW5nc3R1ZGVudA==