apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: khanhash1992/e-commerce-order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_DB_HOST   # Setting Database host address from configMap
          valueFrom:
            configMapKeyRef :
              name: mysql-initdb-config
              key: order-host
        - name: SPRING_DATASOURCE_DB_NAME  # Setting Database name from configMap
          valueFrom:
            configMapKeyRef :
              name: mysql-initdb-config
              key: order-service-db-name
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: order-service-db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: order-service-db-password
---       
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
