apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: user-service-mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-mysql
  template:
    metadata:
      labels:
        app: user-service-mysql
        tier: database
    spec:
      containers:
      - name: user-mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DB_HOST   # Setting Database host address from configMap
          valueFrom:
            configMapKeyRef :
              name: mysql-initdb-config
              key: user-host
        - name: MYSQL_DATABASE
          valueFrom :
            configMapKeyRef :
              name: mysql-initdb-config
              key:  user-service-db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-service-db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-service-db-password
        ports:
        - containerPort: 3306
          name: user-mysql
        volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
      - name: mysql-persistent-storage # Obtaining 'vloume' from PVC
        persistentVolumeClaim:
          claimName: mysql-pv-claim

        
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-mysql
  labels:
    app: user-service-mysql
    tier: database
spec:
  selector:       # mysql Pod Should contain same labels
    app: user-service-mysql
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306